#jekyll config
host: 172.17.60.59
timezone: Asia/Shanghai
encoding: "utf-8"
highlighter: rouge
markdown: kramdown
permalink: /:year/:month/:day/:title/

#my config
url: http://duobab.com
myurl: http://www.duobab.com
date_format: "ordinal"
title: 朵芭比学园
subtitle: "简单记录, 快乐学习！"
description: "朵芭比学园(www.duobab.com)记录了一些技术入门、常用命令等, 主要介绍了Java，Spring,Spring Boot,docker,MySQL,redis等基础知识。"
keywords: duobab, 朵芭比, Spring, Spring Boot, Spring Cloud, 常用命令, Docker, 三分钟学习, 技术支持, 网站搭建, java, redis, IDEA破解

repository: duobab/duobab.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2020-05-03
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: duobab
#organization: duobab
#organization_url: duobab.com
#github_username: duobab
location: Beijing, China
email: duobab_office@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 技术学习

  #-
  #  href: /3min/
  #  label: 3分钟入门

  #-
  #  href: /problem/
  #  label: 问题集合

  -
    href: /idea/
    label: 工具下载

  #-
  #  href: /other/
  #  label: 杂谈

  -
    href: /website/
    label: 文档中心

  -
    href: /command/
    label: 猜你喜欢

  -
    href: /support/
    label: 支持与服务

# ---------------- #
#       RSS        #
# ---------------- #
#subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #

kramdown:
    input: GFM

paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"

plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    command:
        output: true
        permalink: /command/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: duobab
    repo: duobab-comments
    clientID: 38e8b7fb877112cdae44
    clientSecret: e4be1197ff70a6e632cea98b4e6d1e36997d0bde
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-duobab
    adsense:
        footer: false
        sidebar: false 
        content_header: false
        content_footer: false
